version: '3.8'

services:
  split-view:
    build: .
    container_name: ${CONTAINER_NAME:-codekiwi-container}
    ports:
      - "${WEB_PORT:-8080}:80"
      - "${DEV_PORT:-3000}:3000"
    volumes:
      - ${WORKSPACE_DIR}:/workspace
    restart: unless-stopped
