services:
  codekiwi-runtime:
    image: ${CODEKIWI_IMAGE_REGISTRY:-drasdp}/${CODEKIWI_IMAGE_NAME:-codekiwi-runtime}:${VERSION:-${CODEKIWI_IMAGE_TAG_DEFAULT:-latest}}
    container_name: ${CONTAINER_NAME:-${CODEKIWI_CONTAINER_NAME_PREFIX:-codekiwi-runtime}}
    ports:
      - "${WEB_PORT:-${CODEKIWI_WEB_PORT_DEFAULT:-8080}}:${CODEKIWI_NGINX_PORT:-80}"
      - "${DEV_PORT:-${CODEKIWI_DEV_PORT_DEFAULT:-3000}}:${CODEKIWI_DEV_PORT_DEFAULT:-3000}"
    volumes:
      - ${WORKSPACE_DIR}:${CODEKIWI_WORKSPACE_DIR:-/workspace}
      - ${AUTH_DIR:-~/.codekiwi/opencode}:/root/.local/share/opencode
    environment:
      - INSTALL_TEMPLATE=${INSTALL_TEMPLATE:-${CODEKIWI_INSTALL_TEMPLATE_DEFAULT:-yes}}
    restart: ${CODEKIWI_RESTART_POLICY:-unless-stopped}
    env_file:
      - config.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 2s
      timeout: 3s
      retries: 30
      start_period: 10s
