version: '3.8'

services:
  split-view:
    build: .
    container_name: terminal-browser-split
    ports:
      - "8080:80"
      - "3000:3000"
    volumes:
      - ~/CodeKiwi:/workspace
    restart: unless-stopped
