version: '3.8'

services:
  codekiwi-cli:
    image: codekiwi-cli:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${CONTAINER_NAME:-codekiwi-container}
    ports:
      - "${WEB_PORT:-8080}:80"
      - "${DEV_PORT:-3000}:3000"
    volumes:
      - ${WORKSPACE_DIR}:/workspace
    environment:
      - INSTALL_TEMPLATE=${INSTALL_TEMPLATE:-yes}
    restart: unless-stopped
